# Generated by Django 5.1.6 on 2025-02-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Notify", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowrequest",
            name="Duedate",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="borrowrequest",
            name="IssuedDate",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="borrowrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("renewal_requested", "Renewal Requested"),
                    ("renew_accpect", "Renewal Request accepted"),
                    ("renew_reject", "Renewal Request rejected"),
                ],
                default="pending",
                max_length=30,
            ),
        ),
    ]
