# Generated by Django 5.1.6 on 2025-02-25 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Notify", "0002_borrowrequest_duedate_borrowrequest_issueddate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("renewal_requested", "Renewal Requested"),
                    ("renew_accpect", "Renewal Request accepted"),
                    ("renew_reject", "Renewal Request rejected"),
                    ("Cancel_Request", "Request Cancel"),
                ],
                default="pending",
                max_length=30,
            ),
        ),
    ]
