# Generated by Django 5.1.6 on 2025-02-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Notify", "0004_alter_borrowrequest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowrequest",
            name="is_availble",
            field=models.BooleanField(default=True),
        ),
    ]
