# Generated by Django 5.1.6 on 2025-02-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Notify", "0005_borrowrequest_is_availble"),
    ]

    operations = [
        migrations.RenameField(
            model_name="borrowrequest",
            old_name="is_availble",
            new_name="is_available",
        ),
        migrations.AddField(
            model_name="book",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
