# Generated by Django 5.1.6 on 2025-02-25 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Notify", "0006_rename_is_availble_borrowrequest_is_available_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="borrowrequest",
            name="is_available",
        ),
    ]
