# Generated by Django 5.1.6 on 2025-03-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Notify", "0007_remove_borrowrequest_is_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
