# Generated by Django 5.1.6 on 2025-03-03 11:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RefreshTokenStore",
            new_name="RefreshTokenModel",
        ),
    ]
