# Generated by Django 5.1.6 on 2025-03-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="Designation",
            field=models.CharField(default="Data Engineer", max_length=255, null=True),
        ),
    ]
