# Generated by Django 5.1.6 on 2025-04-01 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_employee_designation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeprofile",
            name="profile_picture",
            field=models.ImageField(upload_to="profile_pics/"),
        ),
    ]
