# Generated by Django 5.1.6 on 2025-04-01 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_employeeprofile_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="department",
        ),
        migrations.AddField(
            model_name="employee",
            name="department",
            field=models.ManyToManyField(related_name="employees", to="app.department"),
        ),
    ]
