# Generated by Django 5.1.6 on 2025-03-07 09:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userinfo",
            name="firstname",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="lastname",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="phone",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="RefreshTokenStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.TextField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refresh_tokens",
                        to="app.userinfo",
                    ),
                ),
            ],
        ),
    ]
