# Generated by Django 5.1.6 on 2025-03-17 12:59

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_borrowrequest_duedate_adminactions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowrequest",
            name="Duedate",
            field=models.DateField(default=app.models.BorrowRequest.get_due_date),
        ),
    ]
