# Generated by Django 5.1.6 on 2025-03-18 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_borrowrequest_duedate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="renewalrequests",
            name="processed_date",
        ),
        migrations.RemoveField(
            model_name="renewalrequests",
            name="status",
        ),
    ]
