# Generated by Django 5.1.6 on 2025-03-28 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_remove_renewalrequests_processed_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="refreshtokenstore",
            name="access_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
