# Generated by Django 5.1.6 on 2025-03-28 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_refreshtokenstore_access_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_date", models.DateTimeField(blank=True, null=True)),
                ("issued_date", models.DateTimeField(blank=True, null=True)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("accept_reject_date", models.DateTimeField(blank=True, null=True)),
                ("renewal_request_date", models.DateTimeField(blank=True, null=True)),
                (
                    "renewal_accept_reject_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("return_date", models.DateTimeField(blank=True, null=True)),
                ("cancel_date", models.DateTimeField(blank=True, null=True)),
                ("login_time", models.DateTimeField(blank=True, null=True)),
                ("logout_time", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("renewal_requested", "Renewal Requested"),
                            ("renew_accpect", "Renewal Request accepted"),
                            ("renew_reject", "Renewal Request rejected"),
                            ("Cancel_Request", "Request Cancel"),
                            ("book_returned", "return"),
                        ],
                        default="requested",
                        max_length=20,
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.userinfo"
                    ),
                ),
            ],
        ),
    ]
