# Generated by Django 5.1.6 on 2025-04-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_memberactivity"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="login_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="logout_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
