# Generated by Django 5.1.6 on 2025-02-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apimodel",
            name="email",
            field=models.EmailField(default="dsm952004@gmail.com", max_length=254),
        ),
        migrations.AddField(
            model_name="apimodel",
            name="name",
            field=models.CharField(default="dhara", max_length=200),
        ),
    ]
