# Generated by Django 5.1.6 on 2025-02-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0003_apimodel_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="apimodel",
            name="username",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
